version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioaccesskey
      MINIO_ROOT_PASSWORD: miniosecretkey
      MINIO_BUCKETS: "servidores"
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_ADDRESS: ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - minio_data:/data

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - "9002:9002"
    depends_on:
      - minio

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: servidoresdb
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: employee_manager_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/servidoresdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
      - minio


volumes:
  minio_data:
    driver: local